services:
  - type: web
    name: brama-portal
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: run.py
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: brama-db
          property: connectionString

databases:
  - name: brama-db
    plan: free
