"""Додано поле image_url до Block

Revision ID: 0b9570d3ab47
Revises: 0ae8d65d6650
Create Date: 2025-06-19 15:10:47.454069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9570d3ab47'
down_revision = '0ae8d65d6650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
