"""Add association_balance to settings

Revision ID: 7d21f02eb495
Revises: 48857144b2f0
Create Date: 2025-10-19 17:48:26.685571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d21f02eb495'
down_revision = '48857144b2f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('association_balance', sa.Numeric(precision=10, scale=2), nullable=True), schema='brama')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'association_balance', schema='brama')
    # ### end Alembic commands ###
