"""user extended fields for members, consent, contributions

Revision ID: 816bda69a2da
Revises: c5067de689d1
Create Date: 2025-06-19 20:31:29.195722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816bda69a2da'
down_revision = 'c5067de689d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('specialty', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('join_goal', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('can_help', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('want_to_do', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('is_member', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('consent_given', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('contributions', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('contributions')
        batch_op.drop_column('consent_given')
        batch_op.drop_column('is_member')
        batch_op.drop_column('phone')
        batch_op.drop_column('want_to_do')
        batch_op.drop_column('can_help')
        batch_op.drop_column('join_goal')
        batch_op.drop_column('specialty')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
