"""gallery image as blob

Revision ID: a83af92a1bb1
Revises: 0b9570d3ab47
Create Date: 2025-06-19 19:30:49.222239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a83af92a1bb1'
down_revision = '0b9570d3ab47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('image_mimetype', sa.String(length=64), nullable=True))
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_images', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.drop_column('image_mimetype')
        batch_op.drop_column('image_data')

    # ### end Alembic commands ###
