"""добавлены поля image_data и image_mimetype в модель Block

Revision ID: add_image_data_field
Revises: d3555f676b02
Create Date: 2025-06-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_image_data_field'
down_revision = 'd3555f676b02'  # Замените на последний ID ревизии
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('image_data', sa.LargeBinary(), nullable=True))
    op.add_column('blocks', sa.Column('image_mimetype', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blocks', 'image_mimetype')
    op.drop_column('blocks', 'image_data')
    # ### end Alembic commands ###
