"""add profile photo to user model

Revision ID: add_profile_photo_to_user
Revises: d3555f676b02
Create Date: 2025-06-27 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_profile_photo_to_user'
down_revision = 'd3555f676b02'  # Make sure this points to the current latest migration
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_photo_url', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_photo_url')
    # ### end Alembic commands ###
