"""project image as blob and moderation status

Revision ID: c5067de689d1
Revises: a83af92a1bb1
Create Date: 2025-06-19 19:53:32.535631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5067de689d1'
down_revision = 'a83af92a1bb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('image_mimetype', sa.String(length=64), nullable=True))
        batch_op.drop_column('document_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_url', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.drop_column('image_mimetype')
        batch_op.drop_column('image_data')

    # ### end Alembic commands ###
